# This file was generated by GoReleaser. DO NOT EDIT.
cask "dropln" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "c18200d88b9e801a9424e6e4e7708eee74a54389a7c909ef90b2ef451607395a"
      url "https://github.com/0xydev/dropln/releases/download/v#{version}/dropln_#{version}_macos_x86_64.tar.gz",
        verified: "github.com/0xydev/dropln/"
    end
    on_arm do
      sha256 "88b85666adccbb6387d50b02dd8d91b9ebcc90ee842d10166a2a4922bf917af9"
      url "https://github.com/0xydev/dropln/releases/download/v#{version}/dropln_#{version}_macos_arm64.tar.gz",
        verified: "github.com/0xydev/dropln/"
    end
  end

  on_linux do
    on_intel do
      sha256 "4efa2160f9f88636f8888faa24d9ca0c95e94def2fffde68ea98b567f680f469"
      url "https://github.com/0xydev/dropln/releases/download/v#{version}/dropln_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/0xydev/dropln/"
    end
    on_arm do
      sha256 "c55c5535b75fa0f799440261fc711a9b8ae54e6208887d8ed43f5688073ab503"
      url "https://github.com/0xydev/dropln/releases/download/v#{version}/dropln_#{version}_linux_arm64.tar.gz",
        verified: "github.com/0xydev/dropln/"
    end
  end

  name "dropln"
  desc "Zero-knowledge encrypted ephemeral paste — CLI client"
  homepage "https://dropln.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dropln"
  bash_completion "completions/dropln.bash"
  fish_completion "completions/dropln.fish"
  zsh_completion "completions/_dropln"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dropln"]
    end
  end

  # No zap stanza required

end
