# This file was generated by GoReleaser. DO NOT EDIT.
cask "dropln" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "51807fc898c71bacc8a8608f98e7a0bd87ad43a6b55e11e445aea3e131025e92"
      url "https://github.com/0xydev/dropln/releases/download/v#{version}/dropln_#{version}_macos_x86_64.tar.gz",
        verified: "github.com/0xydev/dropln/"
    end
    on_arm do
      sha256 "156d21b2592323e6c2e4d8a0db721cf973534f5f2a76b8b9741fb70d69124991"
      url "https://github.com/0xydev/dropln/releases/download/v#{version}/dropln_#{version}_macos_arm64.tar.gz",
        verified: "github.com/0xydev/dropln/"
    end
  end

  on_linux do
    on_intel do
      sha256 "179939e71840724ca7c01c477a57b01900d521de363b8bcf641d6acac0524dc6"
      url "https://github.com/0xydev/dropln/releases/download/v#{version}/dropln_#{version}_linux_x86_64.tar.gz",
        verified: "github.com/0xydev/dropln/"
    end
    on_arm do
      sha256 "9ca4f8aa74b5da24d8565f6e2fe529575c647da3145f7b97a0268bd719b92c73"
      url "https://github.com/0xydev/dropln/releases/download/v#{version}/dropln_#{version}_linux_arm64.tar.gz",
        verified: "github.com/0xydev/dropln/"
    end
  end

  name "dropln"
  desc "Zero-knowledge encrypted ephemeral paste — CLI client"
  homepage "https://dropln.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dropln"
  bash_completion "completions/dropln.bash"
  fish_completion "completions/dropln.fish"
  zsh_completion "completions/_dropln"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dropln"]
    end
  end

  # No zap stanza required

end
